### ISSUE TITLE
synchronous callbacks?

### ISSUE THREAD

**Issue by ralphtheninja** [juliangruber/stream-write#1]
https://github.com/juliangruber/stream-write/blob/master/index.js#L14

and

https://github.com/juliangruber/stream-write/blob/master/index.js#L20

**Comment by dcousens** [comment]
@ralphtheninja is the issue you're trying to point out that this behaviour shouldn't be the case?

In my experience it often is the same behaviour with node streams?

**Comment by ralphtheninja** [comment]
It's more a question if it's ok to have them syncronous in this case or not. In general it's bad.
