### ISSUE TITLE
Possible EventEmitter memory leak detected

### ISSUE THREAD

**Issue by ChocolateLoverRaj** [juliangruber/stream-write#6]
Error:
```
(node:27104) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added to [WriteStream]. Use emitter.setMaxListeners() to increase limit
```

I'm pretty sure `once(stream, 'finish')` is causing this leak because I keep calling `streamWrite`, and each time it creates a listener for `finish`.
https://github.com/juliangruber/stream-write/blob/ffbd89a83a8a993a8b4f2392539691d2890a46fb/index.js#L7

It's not really the fault of this library. Idk what the best solution to this is (for now I'm just ignoring the error 😆 )

**Comment by juliangruber** [comment]
Fixed in https://github.com/juliangruber/stream-write/releases/tag/v3.0.0 through the use of `AbortController`: https://github.com/juliangruber/stream-write/commit/a0e0baaa15f48ad09c0988000df161719acdc215
